account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('registrar/', views.register.as_view(), name='registrar')
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>', views.post_detail, name='post_detail'),
    path('sobre-nos/', views.about, name='about'),
    path('contato/', views.contact, name='contact'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):

	POST_STATUS = (
		('active', 'Ativo'),
		('draft', 'Rascunho')
	)
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200)
	body = models.TextField()
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)
	status = models.CharField(max_length=15, choices=POST_STATUS)

	def __str__(self):
	    return self.title

account/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class register(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'account/register.html'

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post

def post_list(request):
	posts = Post.objects.all().order_by('-created_at')
	return render(request, 'blog/post_list.html', {'posts':posts})

def post_detail(request, slug):
	post = get_object_or_404(Post, slug=slug)
	return render(request, 'blog/post_detail.html', {'post':post})

def about(request):
	return render(request, 'blog/about_us.html')

def contact(request):
	return render(request, 'blog/contact.html')

blog/templates/blog/about_us.html
{% extends 'blog/base.html' %}
{% block title %}Título do post{% endblock %}

{% block content %}
	<div class="container">
		<h1>Sobre nós</h1>
		<p>Esta é a história do blog...</p>
	</div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:about' %}">Sobre nós</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:contact' %}">Contato</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Sair</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost:8000/account/registrar">Cadastro</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      <div class="row">
        {% if user.is_authenticated %}
        <p class="logged-in-p">
          Olá {{ user.username }} seja bem vindo, o que deseja fazer hoje? 
        <span class="sair"><a href="{% url 'logout' %}">Sair</a></span>
        </p>
        {% endif %}
          {% block content %}
          {% endblock %}
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% block title %}Título do post{% endblock %}

{% block content %}
	<div class="container">
		<h1>Quer entrar em contato conosco?</h1>
	</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
	<div class="container">
		<h1>{{ post.title }}</h1>
		<p>Publicado em {{ post.created_at }} por {{ post.author }}</p>
		<p>{{ post.body|linebreaks }}</p>
	</div> 
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block title %}Listagem de Posts{% endblock %}

{% block content %}
	<div class="container">
		<div class="jumbotron jumbotron-fluid">
		  <div class="container">
		    <h1 class="display-4">Bem vindo ao Django blog!</h1>
		    <p class="lead">Aqui você vai encontrar os melhores posts sobre o framework.</p>
		  </div>
		</div>
		<div class="row">
				{% for post in posts %}
		    <div class="col">
		      <div class="card" style="width: 18rem;">
		        <img class="card-img-top" src="https://via.placeholder.com/286x180" alt="Card image cap">
		        <div class="card-body">
		          <h5 class="card-title">{{ post.title }}</h5>
							<p class="card-text">{{ post.body|truncatechars:50 }}...</p>
							<p>Criado em {{ post.created_at }} por {{ post.author }}</p>
		          <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-primary">Ver o post completo</a>
		        </div>
		      </div>
				</div>
				{% endfor %}
		</div>
	</div> 
{% endblock %}